#!/usr/bin/with-contenv bash

set -u # Unset Variables are an error
set -e # Exit on error


# Check process and kill if running
check_and_terminate_process 'nginx'

# Ensure tmp folder exists
if [ ! -d '/tmp/nginx'  ]; then
    mkdir -p /tmp/nginx
fi

chown -R 901:901 /tmp/nginx
chmod -R 0755 /tmp/nginx

# Ensure Log folder exists
if [ ! -d '/config/log/nginx'  ]; then
    mkdir -p /config/log/nginx/
    touch /config/log/nginx/error.log
fi

chown -R 901:901 /config/log/nginx
chmod -R 0755 /config/log/nginx

chown -R 901:901 /etc/nginx
chmod -R 0755 /etc/nginx

log "nginx" "Starting . . ."
exec 2>&1 /bin/s6-notifyoncheck -d -w 500 \
          /usr/sbin/nginx \
          -c /etc/nginx/nginx.conf \
          -g 'daemon off;'
